---
- name: Week 4 Lab
  hosts: all
  become: true

  tasks: 
    - name: Install Firefox
      ansible.builtin.dnf:
        name: firefox
        state: latest

    - name: Install Git
      ansible.builtin.dnf:
        name: git
        state: latest 

    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Import Google Chrome key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.google.com/linux/linux_signing_key.pub

    - name: Install the Google Chrome rpm from a remote repo
      ansible.builtin.dnf:
        name: 'https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm'
        state: present

    - name: Install MariaDB
      ansible.builtin.dnf:
        name: mariadb
        state: latest

    - name: Copy HTML files to Linux machine
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: /var/www/html
      loop:
      - src: sample1.html
      - src: sample2.html
      - src: sample3.html

    
    - name: Remove Google Chrome
      ansible.builtin.dnf:
        name: google-chrome-stable
        state: absent

    - name: Reboot machine
      ansible.builtin.reboot:

    - name: Wait for machine to Reboot
      ansible.builtin.wait_for_connection:

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Restart service httpd, in all cases
      ansible.builtin.service:
        name: httpd
        state: restarted

    #This is totally a bugfix